### ISSUE TITLE
Packaging your plugin for the asset library

### ISSUE THREAD

**Issue by akien-mga** [Zylann/godot_terrain_plugin#1]
The web frontend of Godot's asset library for 2.1 is now starting to be usable (albeit in alpha mode): https://godotengine.org/asset-library/frontend/asset/

It would be nice if you could have a look at packaging this awesome plugin for the assetlib, so that we start having content there to test the platform, see its bugs, etc. :)

CC @bojidar-bg

**Comment by Zylann** [comment]
I should that at the end of the day, before I need to modify the directory because `addons/terrain` is too easy to collide with IMO :)

**Comment by Zylann** [comment]
Hmm so far I had the demo project in this repo, because it is convenient to test things on my end. But now it will end up in the assetlib. I could make a separate repo for it, but then testing will become more difficult due to the requirement of updating the addon everytime I change something, and vice-versa if the addon changes I'll have to update the demo.
I'll leave it as it is for now, but this has to change. Not sure what is the best solution yet. Any ideas welcome :)

**Comment by akien-mga** [comment]
Yeah, that's part of why I'm very unhappy with the current packaging system that forces everything into `res://` as I mentioned in the other issue. IMO it's fine to have the demo together with the plugin, as it helps users understand how to use the plugin. But you might have to move it to a subfolder that wouldn't conflict with users' project files I guess.

**Comment by Zylann** [comment]
Well, engine.cfg will still have a big conflict :s

Also, I asked this as demos of my plugin are likely to grow in size, because they are... well, terrains. 1024x1024 float heightfields with painting information and baked meshes ahead :p

**Comment by Zylann** [comment]
I submitted an entry for my asset but I don't see it in the library. Also, if I click "revise" I get this:

```

Notice: Undefined index: original in /data/web/df/e1/53/godotengine.org/htdocs/asset-library/templates/edit_asset_edit.phtml on line 2

Warning: array_merge(): Argument #1 is not an array in /data/web/df/e1/53/godotengine.org/htdocs/asset-library/templates/edit_asset_edit.phtml on line 2
```

**Comment by akien-mga** [comment]
It's in the moderation queue so it's normal that you don't see it in the library, I'll have a look at accepting it. Could you open an issue on https://github.com/godotengine/asset-library about the error you're seeing though?

**Comment by bojidar-bg** [comment]
Oops, seems like I forgot to handle a case with submitted assets.... _Edit_ Should be working fine now.

**Comment by akien-mga** [comment]
@Zylann It's up: https://godotengine.org/asset-library/frontend/asset/4 \o/

Note that the assetlib needs the sha256sum of the zip archive to validate it, which means that the version currently validated is the master branch as of today, but if you push new commits, the assetlib entry will be invalidated as the new zip archive won't match the validated one.

To work it around you can submit a link to a given commit zip archive, e.g. https://github.com/Zylann/godot_terrain_plugin/archive/3aa47b3d011e20597e00e293a4689232b5be5706.zip
This way the link will stay valid even if you push new developments (but of course you'll have to update the assetlib entry anyway if you want the latest version to be available).

**Comment by Zylann** [comment]
Or I could upload a zip to my own server so the link will be stable and I can update it by my own means, with the relevant content :)

**Comment by akien-mga** [comment]
That's a possibility too, but remember that the sha256sum of your zip will change too when you update its contents, so you won't circumvent the need to have the new archive validated. :)

**Comment by Zylann** [comment]
Arf, true... I'll have to go to the website everytime then... by the way, is the asset actually stored on the website?

**Comment by akien-mga** [comment]
Nope only the link is stored, and the sha256sum has to be entered to validate the asset (currently it's done manually by the moderator, but in the end the assetlib should evaluate it itself).

**Comment by Zylann** [comment]
I try to update the plugin on the website, but I can't get past the screen showing differences, the only choice I have is "revise". If I leave the page, all information is lost and I have to refill it again.

**Comment by akien-mga** [comment]
It seems to have worked fine, I have an entry to moderate.

**Comment by Zylann** [comment]
Note to myself: I should do some cleaning for users to easily discard demo files. And also decide something for #3, as it also depends on https://github.com/godotengine/godot/issues/6023
