### ISSUE TITLE
Add support for SRTM data

### ISSUE THREAD

**Issue by HeadClot** [Zylann/godot_terrain_plugin#14]
Support for [Shuttle Radar Topography Mission](https://www2.jpl.nasa.gov/srtm/) height map data would be awesome so that we can re create real world locations inside godot.

**Comment by Zylann** [comment]
I halted development on this plugin, it's now just for reference or prototyping.
Have a look at this repo for a more actively maintained version: https://github.com/Zylann/godot_heightmap_module

Depending on how you get this data, you could already fill the heighfield using samples from it.

**Comment by HeadClot** [comment]
Thanks for the heads up @Zylann 

I will close this issue now. Since this repo is no longer being maintained.
