### ISSUE TITLE
Multi-Edit Feature Request

### ISSUE THREAD

**Issue by suptoasty** [Zylann/godot_terrain_plugin#5]
It would be easier to develop multiple variations of a simple terrain type like a plateau, if you can find a way to get the brushes to support Godot's multi-node edit feature. This would speed up development (granted this would not be a big boost in productivity, but would still save anywhere from 30 seconds to 4 minutes) for games like Skyrim where the terrain is the same base height map with deviations in whether or not this section holds a mountain that has a divot in the top like a volcano, versus this section that has the exact same mountain with no divot. I don't know if that was a clear picture of what I had in mind, but I can try to clarify at your request.

**Comment by Zylann** [comment]
Can you indeed clarify ^^ ?
Godot multi-edition is for multiple selected nodes, I don't see how it's used in what you describe.
Images would help I think.

**Comment by suptoasty** [comment]
Never mind kinda stupid idea, and impossible to implement. Closing issue
