### ISSUE TITLE
Resizing a Terrain visual artifact

### ISSUE THREAD

**Issue by suptoasty** [Zylann/godot_terrain_plugin#6]
When resizing a terrain from values higher than 16.......to values less than 16.....then higher than 16 again, part of the terrain disappears from the 3D editor until I use a brush.

Linux Mint 18, Godot Engine 2.1 Stable

Steps to reproduce:
1. set terrain size to 32
2. set terrain size to a value less than 16
3. set terrain size to a value greater than 16
4. use brush on terrain

Note:  
This is a visual artifact only no errors occur. It may be related to my previous issue:
[https://github.com/Zylann/godot_terrain_plugin/issues/4](url)
also happens if terrain size is set to 16 then 15 then 17

Screenshot:
![screenshot at 2016-08-12 21-03-08](https://cloud.githubusercontent.com/assets/16758490/17640908/36240ec8-60d1-11e6-965a-4c861c5fe196.png)

**Comment by Zylann** [comment]
I thought I fixed this one earlier in development, but I still get it as well. It has no impact ingame, and reloading the scene should show the missing visuals. Looks like I didn't handled a specific case when resizing (because I don't recompute everything since it's very expensive).

**Comment by suptoasty** [comment]
"Looks like I didn't handled a specific case when resizing (because I don't recompute everything since it's very expensive)." 

That is understandable. I'm fine with this artifact, but felt that you should know it's there.

**Comment by Zylann** [comment]
The fix should be available on the assetlib, let me know if you still have the problem

**Comment by suptoasty** [comment]
Hey @Zylann, just letting you know I'm no longer having any problems after updating the plug-in. You're free to close this issue if you want.
